registerApp/urls.py
from django.urls import path
from . import views


app_name = 'registerApp'

urlpatterns = [
    path('', views.landing, name="landing"), 
    path('login/', views.userLogin, name="login"),
    path('register/', views.register, name="register"),
    # path('activate/<uidb64>/<token>', views.activate, name='activate'),

    path('logout/', views.userLogout, name="logout"),
    # path('book_search/', views.book_search, name='book_search'),
    path('add_to_readlist/<str:title>/', views.add_to_readlist, name='add_to_readlist'),
    path('add_to_favourites/<str:title>/', views.add_to_favourites, name='add_to_favourites'),
    path('readlist/', views.readlist, name='readlist'),
    path('favourites/', views.favourites, name='favourites'),
    path('remove_from_readlist/<str:title>/', views.remove_from_readlist, name='remove_from_readlist'),
    path('remove_from_favourites/<str:title>/', views.remove_from_favourites, name='remove_from_favourites'),
    path('profile/', views.profile, name='profile'),
    path('profile/update/', views.profile_update, name='profile_update'),
    path('index/', views.index, name='index'),
    path('book/<str:isbn>/', views.book_detail, name='book_detail'),
    path('token/' , views.token_send , name="token_send"),
    path('success/' , views.success , name='success'),
    path('verify/<auth_token>/' , views.verify , name="verify"),
    path('error/' , views.error_page , name="error")
    
]

userRegistration/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from registerApp import views

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('registerApp.urls')),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset_form.html'), name="password_reset"),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name="password_reset_done"),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name="password_reset_confirm"),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name="password_reset_complete"),
    path('login/', auth_views.LoginView.as_view(template_name='userLogin.html'), name='login'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registerApp/models.py
from django.db import models
from django.contrib.auth.models import User


class Readlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.JSONField()


class Favourites(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.JSONField()




class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    username = models.CharField(max_length=150, blank=True)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    email = models.EmailField(max_length=254, blank=True)
    location = models.CharField(max_length=255, blank=True)
    profile_picture = models.ImageField(upload_to='profile_images/', blank=True, null=True)

    def __str__(self):
        return self.user.username
    
    
class Profile(models.Model):
    user = models.OneToOneField(User , on_delete=models.CASCADE)
    auth_token = models.CharField(max_length=100 )
    is_verified = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username
    

registerApp/forms.py
# forms.py
from django import forms
from .models import UserProfile

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_picture', 'username', 'first_name', 'last_name', 'email', 'location']

registerApp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import JsonResponse
from .forms import UserProfileForm
from django.shortcuts import get_object_or_404
from .models import Readlist, Favourites, UserProfile
from django.views.decorators.csrf import csrf_exempt
from django.db import transaction 
import json
import string
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
import re
from django.contrib.auth import login
from django.conf import settings
from registerApp.models import Profile
from .models import *
from django.core.mail import send_mail
import uuid
import random
from .models import Readlist
from itertools import zip_longest




def userLogin(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user_obj = User.objects.filter(username = username).first()
        if user_obj is None:
            messages.success(request, 'User not found.')
            return redirect('registerApp:login')
        
        
        profile_obj = Profile.objects.filter(user = user_obj ).first()

        if not profile_obj.is_verified:
            messages.success(request, 'Profile is not verified check your mail.')
            return redirect('registerApp:login')

        user = authenticate(username = username , password = password)
        if user is None:
            messages.success(request, 'Wrong password.')
            return redirect('registerApp:login')
        
        login(request , user)
        return redirect('registerApp:index')

    return render(request , 'registerApp/userLogin.html')





# def register(request):
#     if request.method == 'POST':
#         username = request.POST.get('username')
#         email = request.POST.get('email')
#         password = request.POST.get('password')
#         first_name = request.POST.get('first_name')
#         last_name = request.POST.get('last_name')

#         try:
#             if User.objects.filter(username=username).first():
#                 messages.success(request, 'Username is taken.')
#                 return redirect('registerApp:register')

#             if User.objects.filter(email=email).first():
#                 messages.success(request, 'Email is taken.')
#                 return redirect('registerApp:register')

#             user_obj = User(username=username, email=email, first_name=first_name, last_name=last_name)
#             user_obj.set_password(password)
#             user_obj.save()

#             auth_token = str(uuid.uuid4())

#             user_profile = UserProfile.objects.create(user=user_obj, username=username, email=email, location=request.POST.get('location'), first_name=first_name, last_name=last_name)
#             user_profile.save()

#             profile_obj = Profile.objects.create(user=user_obj, auth_token=auth_token)
#             profile_obj.save()

#             send_mail_after_registration(email, auth_token)
#             return redirect('registerApp:token')

#         except Exception as e:
#             print(e)

#     return render(request, 'registerApp/userRegister.html')



def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        location = request.POST.get('location')

        # Check if all fields are entered
        missing_fields = []
        if not username:
            missing_fields.append('Username')
        if not email:
            missing_fields.append('Email')
        if not password:
            missing_fields.append('Password')
        if not confirm_password:
            missing_fields.append('Confirm Password')
        if not first_name:
            missing_fields.append('First Name')
        if not last_name:
            missing_fields.append('Last Name')
        if not location:
            missing_fields.append('Location')

        if missing_fields:
            messages.error(request, f'Please fill in all the fields: {", ".join(missing_fields)}.')
            return redirect('registerApp:register')

        if password != confirm_password:
            messages.error(request, 'Passwords do not match.')
            return redirect('registerApp:register')

        # Check username format
        if not re.match(r'^[a-zA-Z0-9_]+$', username):
            messages.error(request, 'Username should only contain alphanumeric characters and underscore.')
            return redirect('registerApp:register')

        # Check first name format
        if not first_name.isalpha():
            messages.error(request, 'First name should only contain characters.')
            return redirect('registerApp:register')

        # Check last name format
        if not last_name.isalpha():
            messages.error(request, 'Last name should only contain characters.')
            return redirect('registerApp:register')

        # Check password complexity
        if len(password) < 8:
            messages.error(request, 'Your password must contain at least 8 characters.')
            return redirect('registerApp:register')
        elif not any(char.isdigit() for char in password):
            messages.error(request, 'Your password must contain at least one numeric character.')
            return redirect('registerApp:register')
        elif not any(char in string.punctuation for char in password):
            messages.error(request, 'Your password must contain at least one special character.')
            return redirect('registerApp:register')
        elif any(field.lower() in password.lower() for field in [username]):
            messages.error(request, 'Your password can’t be too similar to your username')
            return redirect('registerApp:register')

        try:
            # Check if username already exists
            if User.objects.filter(username=username).exists():
                messages.error(request, 'Username is already in use.')
                return redirect('registerApp:register')

            # Check if email already exists
            if User.objects.filter(email=email).exists():
                messages.error(request, 'Email is already registered.')
                return redirect('registerApp:register')

            user_obj = User.objects.create_user(username=username, email=email, password=password, first_name=first_name, last_name=last_name)
            auth_token = str(uuid.uuid4())

            user_profile = UserProfile.objects.create(user=user_obj, username=username, email=email, location=location, first_name=first_name, last_name=last_name)
            user_profile.save()

            profile_obj = Profile.objects.create(user=user_obj, auth_token=auth_token)
            profile_obj.save()

            domain = request.build_absolute_uri('/')[:-1]
            send_mail_after_registration(email, auth_token, domain)
            return redirect('registerApp:token')

        except Exception as e:
            print(e)

    return render(request, 'registerApp/userRegister.html')


def success(request):
    return render(request , 'registerApp/success.html')


def token_send(request):
    return render(request , 'registerApp/token_send.html')



def verify(request , auth_token):
    try:
        profile_obj = Profile.objects.filter(auth_token = auth_token).first()
    

        if profile_obj:
            if profile_obj.is_verified:
                messages.success(request, 'Your account is already verified.')
                return redirect('registerApp:login')
            profile_obj.is_verified = True
            profile_obj.save()
            messages.success(request, 'Your account has been verified.')
            return redirect('registerApp:login')
        else:
            return redirect('registerApp:error')
    except Exception as e:
        print(e)
        return redirect('/')

def error_page(request):
    return  render(request , 'registerApp/error.html')



def send_mail_after_registration(email , token, domain):
    subject = 'Your accounts need to be verified'
    message = f'Hi paste the link to verify your account {domain}/verify/{token}'
    email_from = settings.EMAIL_HOST_USER
    recipient_list = [email]
    send_mail(subject, message , email_from ,recipient_list )




def userLogout(request):
    logout(request)
    return redirect('registerApp:landing')



def landing(request):
    return render(request, 'registerApp/landing.html')


def pass_reset(request):
    return render(request, 'registerApp/pass_reset.html')



@login_required
@csrf_exempt  
def add_to_readlist(request, title):
    if request.method == 'POST':
        user = request.user
        try:
            data = json.loads(request.body)
            authors = data.get('authors', '')
            previewLink = data.get('previewLink', '')
            thumbnail = data.get('thumbnail', '')
            book = {
                'title': title,
                'authors': authors,
                'previewLink': previewLink,
                'thumbnail': thumbnail,
            }

            existing_entry = Readlist.objects.filter(user=user, book=book).first()
            if existing_entry:
                return JsonResponse({'message': 'Book is already in the Readlist'})
            
            Readlist.objects.create(user=user, book=book)

            return JsonResponse({'message': 'Book added to Readlist successfully'})
        except json.JSONDecodeError:
            return JsonResponse({'error': 'Invalid JSON data'}, status=400)

    return JsonResponse({'error': 'Invalid request method'}, status=405)

@login_required
@csrf_exempt  

registerApp/templates/registerApp/profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'registerApp/images/favicon.ico' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
    <title>Stylish Profile</title>
    <style>
        body {
            margin: 0;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #f7f7f7;
        }

        .top-image {
            position: relative;
            width: 100%;
            height: 200px;
            overflow: hidden;
            z-index: 1; /* Set a lower z-index */
        }

        .top-image img {
            width: 100%;
            height: 100%;
            object-fit: cover;
        }

        .top-image a {
            position: absolute;
            top: 20px;
            left: 20px;
            color: #fff;
            text-decoration: none;
            font-size: 24px;
        }

        .profile-container {
            position: relative;
            z-index: 2;
        }

        .upload {
            text-align: center;
            margin-top: -80px;
        }

        .upload img {
            border-radius: 50%;
            border: 3px solid #fff;
            margin-top: 11px;
            height: 150px;
            width: 150px;
            object-fit: cover;
            transition: transform 0.3s ease-in-out;
            margin-bottom: 30px;
        }

        .upload .round {
            position: absolute;
            bottom: 0;
            right: 0;
            background: #00B4FF;
            width: 40px;
            height: 40px;
            line-height: 40px;
            text-align: center;
            border-radius: 50%;
            overflow: hidden;
            cursor: pointer;
            transition: background 0.3s ease-in-out;
        }

        .upload .round input[type="file"] {
            position: absolute;
            transform: scale(2);
            opacity: 0;
            cursor: pointer;
        }

        .upload:hover img {
            transform: scale(1.1);
        }

        .upload .round:hover {
            background: #007bb5;
        }

        .profile-details {
            text-align: center;
            padding: 30px;
            background-color: #fff;
            border-radius: 15px;
            box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);
            margin: -70px auto 50px;
            max-width: 1000px;
        }

        .profile-details label {
            font-size: 18px;
            font-weight: bold;
            color: #333;
            margin-top: 10px;
            display: block;
        }

        .profile-details h2 {
            font-size: 22px;
            color: #333;
            margin: 10px 0;
        }

        .user-details,
        .user-fav {
            display: flex;
            justify-content: space-around;
            margin-top: 50px;
        }

        .user-fav .userReadlist,
        .user-fav .userFavourites {
            padding: 20px;
            width: 130px;
            background-color: #babcc3;
            border-radius: 10px;
            transition: transform 0.3s ease-in-out;
        }

        .user-fav .userReadlist:hover,
        .user-fav .userFavourites:hover {
            transform: scale(1.05);
        }

        .user-fav .userReadlist label,
        .user-fav .userFavourites label {
            color: #4caf50;
            font-weight: bold;
        }

        .updateButton button {
            width: 150px;
            height: 40px;
            border-radius: 40px;
            border: 2px solid #fff;
            background-color: #4caf50;
            color: #fff;
            cursor: pointer;
            transition: background 0.3s ease-in-out, transform 0.3s ease-in-out;
            margin-top: 50px;
        }

        .updateButton button:hover {
            background-color: #45a049;
            transform: scale(1.05);
        }

        .profile-details a {
            text-decoration: none;
            color: #333;
            font-weight: bold;
            font-size: 13px;
        }
        @media only screen and (max-width: 600px) {
            .top-image {
                height: 150px;
            }
    
            .top-image a {
                font-size: 18px;
            }
    
            .upload img {
                height: 120px;
                width: 120px;
            }
    
            .upload .round {
                width: 30px;
                height: 30px;
                line-height: 30px;
                font-size: 14px;
            }
    
            .profile-details {
                padding: 20px;
                margin: -50px auto 20px;
            }

    
            .user-details,
            .user-fav {
                flex-direction: row;
                flex-wrap: wrap;
            }
    
            .user-fav .userReadlist,
            .user-fav .userFavourites {
                width: 100%;
                margin-bottom: 10px;
            }
    
            .updateButton button {
                width: 100%;
            }
        }
    </style>
</head>

<body>
    <div class="top-image">
        <img src="{% static 'registerApp/images/book_img.png' %}" alt="">
        <a href="{% url 'registerApp:index' %}">
            <i class="fas fa-arrow-left"></i>
        </a>
    </div>

    <div class="profile-container">
        <div class="upload">
            {% if user_profile.profile_picture %}
            <img src="{{ user_profile.profile_picture.url }}" alt="">
            {% else %}
            <img src="{% static 'registerApp/images/noprofil.jpg' %}" alt="">
            {% endif %}
            {% comment %} <div class="round">
                <input type="file" name="profile_picture" id="profilePictureInput" onchange="previewProfilePicture()">
                <i class="fas fa-camera" style="color: #fff;"></i>
            </div> {% endcomment %}
        </div>

        <div class="profile-details">
            <label for="userName">{{ user_profile.user.username }}</label>
            <label for="location">{{ user_profile.location}}</label>
            <div class="user-details">
                <div class="fName">
                    <h2>First Name</h2>
                    <label for="firstName">{{ user_profile.user.first_name }}</label>
                </div>
                <div class="lName">
                    <h2>Last Name</h2>
                    <label for="lastName">{{ user_profile.user.last_name }}</label>
                </div>
                <div class="email">
                    <h2>Email</h2>
                    <label for="email">{{ user_profile.user.email }}</label>
                </div>
            </div>
            <div class="user-fav">
                <div class="userReadlist">
                    <label for="read_count">{{ user_readlist_count }}</label>
                    <h2>Readlist</h2>
                </div>
                <div class="userFavourites">
                    <label for="fav_count">{{ user_favourites_count }}</label>
                    <h2>Favourites</h2>
                </div>
            </div>
            <div class="updateButton">
                <button type="button"><a href="{% url 'registerApp:profile_update' %}">Update Profile</a></button>
            </div>
        </div>
    </div>

    <script src="{% static 'registerApp/js/index.js' %}"></script>
</body>

</html>

registerApp/templates/registerApp/profile_update.html
<!-- templates/registerApp/profile_update.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Profile</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }
    
        .container {
            display: flex;
            flex-direction: column;
            align-items: center;
        }
    
        .sub-con {
            width: 130%;
            max-width: 400px;
            padding: 20px;
            background-color: #ffffff;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }
    
        h1 {
            text-align: center;
            color: #333;
        }
    
        form {
            margin-top: 20px;
        }
    
        label {
            display: block;
            margin-bottom: 8px;
            color: #555;
        }
    
        input[type="text"],
        input[type="password"],
        input[type="email"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
            outline: none;
        }
    
        button {
            background-color: #4caf50;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            margin-left: 115px;
        }
    
        button:hover {
            background-color: #45a049;
        }
    
        .error-message {
            color: red;
            margin-top: 10px;
        }
    
        @media only screen and (max-width: 600px) {
            .sub-con {
                width: 90%;
                padding: 15px;
            }
            button {
                margin-left: 65px;
            }
        }
    </style>
    
</head>
<body>
    <div class="container">
        <div class="sub-con">
            <h1>Update Profile</h1>
            <form method="post" action="{% url 'registerApp:profile_update' %}" enctype="multipart/form-data">
                {% csrf_token %}

                {{ form.profile_picture.label_tag }}
                {{ form.profile_picture }}
                <br>


                {{ form.username.label_tag }}
                {{ form.username }}
                <br>

                {{ form.first_name.label_tag }}
                {{ form.first_name }}
                <br>

                {{ form.last_name.label_tag }}
                {{ form.last_name }}
                <br>

                {# Hide the email label and manually create an input field #}
                <label for="{{ form.email.id_for_label }}" style="display: none;">{{ form.email.label_tag }}</label>
                <input type="email" name="{{ form.email.name }}" value="{{ form.email.value }}" id="{{ form.email.id_for_label }}" style="display: none;">
                <br>
                                
                <button type="submit">Save Changes</button>
            </form>

            {% if form.errors %}
                <p style="color: red;">{{ form.errors }}</p>
            {% endif %}
        </div>
    </div>
</body>
</html>

registerApp/templates/registerApp/readlist.html
<!-- books/templates/books/readlist.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Readlist</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f5f5f5;
            padding: 0px;
            margin: 0px;
        }

        .navbar {
            position: sticky;
            top: 0;
            background-color: #ffff;
            padding: 20px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            z-index: 100; /* Ensure the navbar is above other content */
          }
          
          .navbar a {
            text-decoration: none;
            color: #333;
            margin: 0 15px;
            font-weight: 600;
          }
          
          .navbar a:hover {
            color: #007bff;
          }

          .navbar .hamburger {
            display: none;
            cursor: pointer;
          }

          .logo {
            padding: 0 32px;
            font-weight: 900;
            font-size: 24px;
          }

        h1 {
            color: #333;
            text-align: center;
        }

        ul {
            list-style: none;
            padding: 0;
            margin: 0;
            display: flex;
            flex-direction: row;
            justify-content: space-around;
            flex-wrap: wrap;
        }

        li {
            background: linear-gradient(#3498db, rgba(0, 0, 0, 0));
            padding: 10px;
            margin: 10px 0;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            overflow: hidden;
            width: 500px;
            height: 300px;
            display: flex;
            flex-direction: row;
        }

        li .container img {
            height: 200px;
        }

        li .sub-con {
            padding-left: 80px;
            padding-top: 200px;
        }

        h3 {
            color: #fff;
            margin: 0 0 10px;
        }

        p {
            color: #ecf0f1;
            margin: 0 0 5px;
        }

        img {
            max-width: 100%;
            height: auto;
            border-radius: 5px;
        }

        form {
            margin-top: 10px;
        }

        button {
            background-color: #e74c3c;
            color: #fff;
            border: none;
            padding: 8px 15px;
            border-radius: 3px;
            cursor: pointer;
        }

        .menu-nav-links > a:nth-child(1) {
            text-decoration: none;
            margin-left: auto;
         }

  .menu-nav-links {
    /* display: none;
    flex-direction: column;
    align-items: center;
    position: absolute;
    background-color: #f9f9f9;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2); */
    position: fixed;
    top: 0;
    right: 0;
    height: 250px;
    width: 250px;
    z-index: 999;
    background-color: white;
    box-shadow: -10px 0 10px  rgb(0, 0, 0, 0.1);
    display: none;
    flex-direction: column;
    justify-content: space-evenly;
    align-items: center;
  }

        @media (max-width: 768px) {
            .navbar {
                width: 100%;
                position: fixed;
                height: 50px;
                display: flex;
              }
          
              .nav-links {
                display: none;
                flex-direction: column;
                align-items: center;
                display: none;
                position: absolute;
                background-color: #f9f9f9;
                min-width: 160px;
                box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
              }
          
              .nav-links a {
                color: black;
                padding: 12px 16px;
                text-decoration: none;
                display: block;
              }
          
              .nav-links.show {
                display: flex;
              }
          
              .navbar .hamburger {
                display: block;
                height: 35px;
                width: 35px;
                padding-right: 25px;
              }

              h1 {
                margin-top: 100px;
              }

              .logo {
                padding: 0px;
              }
        }

    </style>
</head>
<body>

    <nav class="navbar">
        <div class="logo">  
          <a href="{% url 'registerApp:index' %}">BookStore</a>
        </div>
        <div class="menu-nav-links">
            <a href="" class="cls-img">&#x2715;</a>
            <a href="{% url 'registerApp:index' %}">Home</a>
            <a href="{% url 'registerApp:readlist' %}">Readlist</a>
            <a href="{% url 'registerApp:favourites' %}">Favourites</a>
            <a href="{% url 'registerApp:profile' %}">Profile</a>
            <a href="{% url 'registerApp:logout' %}">Logout</a>
          </div>
          <div class="nav-links">
            <a href=""></a>
            <a href="{% url 'registerApp:index' %}">Home</a>
            <a href="{% url 'registerApp:readlist' %}">Readlist</a>
            <a href="{% url 'registerApp:favourites' %}">Favourites</a>
            <a href="{% url 'registerApp:profile' %}">Profile</a>
            <a href="{% url 'registerApp:logout' %}">Logout</a>
          </div>
        <div class="hamburger" onclick=showSidebar()>&#9776;</div>
      </nav>
    
      <script>
        function showSidebar () {
            const sidebar = document.querySelector('.menu-nav-links')
            sidebar.style.display = 'flex';
          }
        </script>
    <h1>Readlist</h1>

    {% if zipped_data %}
    <ul>
        {% for book, color in zipped_data %}
            <li style="background-color: {{ color }}">
                <div class="container">
                    <h3>{{ book.title }}</h3>
                    <p>Author: {{ book.authors }}</p>
                    <a href="{{ book.previewLink }}" target="_blank"><img src="{{ book.thumbnail }}" alt="{{ book.title }} thumbnail"></a>
                </div>
                <div class="sub-con">
                    <form method="post" action="{% url 'registerApp:remove_from_readlist' book.title %}">
                        {% csrf_token %}
                        <button type="submit">Remove from Readlist</button>
                    </form>
                </div>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No books in the readlist.</p>
{% endif %}



</body>
</html>